config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  #resources :form_entries
  resources :calendars
  resources :forms do 
    resources :form_entries
  end 
  resources :schedules
  resources :availabilities
  devise_for :users

  root to: 'dashboards#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/calendar.rb
# Calendar Model references an individual calendar where the user will define scheduling, holidays etc..

class Calendar < ApplicationRecord
  belongs_to :user
  has_many :schedules
  has_many :appointments
  has_many :availabilities

  has_many :form_calendars, :dependent => :destroy 
  has_many :forms, through: :form_calendars
  accepts_nested_attributes_for :form_calendars

  validates :name, presence: true 
  # Interval of the calendar cannot be longer than a full day in minutes
  validates :interval, numericality: { greater_than: 0, less_than_or_equal_to: 1440 }
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :set_calendar, only: %i[ show edit update destroy ]

  # GET /calendars or /calendars.json
  def index
    @calendars = Calendar.all
  end

  # GET /calendars/1 or /calendars/1.json
  def show
    @appointments = @calendar.appointments
  end

  # GET /calendars/new
  def new
    @calendar = Calendar.new
  end

  # GET /calendars/1/edit
  def edit
  end

  # POST /calendars or /calendars.json
  def create
    @calendar = Calendar.new(calendar_params)

    respond_to do |format|
      if @calendar.save
        format.html { redirect_to @calendar, notice: "Calendar was successfully created." }
        format.json { render :show, status: :created, location: @calendar }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calendars/1 or /calendars/1.json
  def update
    respond_to do |format|
      if @calendar.update(calendar_params)
        format.html { redirect_to @calendar, notice: "Calendar was successfully updated." }
        format.json { render :show, status: :ok, location: @calendar }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calendars/1 or /calendars/1.json
  def destroy
    @calendar.destroy
    respond_to do |format|
      format.html { redirect_to calendars_url, notice: "Calendar was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calendar
      @calendar = Calendar.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def calendar_params
      params.require(:calendar).permit(:name, :description, :user_id, :interval)
    end
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/views/calendars/_form.html.erb
<%= form_with(model: calendar) do |form| %>
  <% if calendar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(calendar.errors.count, "error") %> prohibited this calendar from being saved:</h2>

      <ul>
        <% calendar.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :interval %>
    <%= form.number_field :interval %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="max-w-lg">
  <%= month_calendar do |date| %>
    <%= date.day %>
  <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/calendars/edit.html.erb
<h1>Editing Calendar</h1>

<%= render 'form', calendar: @calendar %>

<%= link_to 'Show', @calendar %> |
<%= link_to 'Back', calendars_path %>

app/views/calendars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Calendars</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>User</th>
      <th>Interval</th>
      <th>Calendar ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @calendars.each do |calendar| %>
      <tr>
        <td><%= calendar.name %></td>
        <td><%= calendar.description %></td>
        <td><%= calendar.user_id %></td>
        <td><%= calendar.interval %></td>
        <td><%= calendar.id %></td>
        <td><%= link_to 'Show', calendar %></td>
        <td><%= link_to 'Edit', edit_calendar_path(calendar) %></td>
        <td><%= link_to 'Destroy', calendar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Calendar', new_calendar_path %>

app/views/calendars/new.html.erb
<h1>New Calendar</h1>

<%= render 'form', calendar: @calendar %>

<%= link_to 'Back', calendars_path %>

app/views/calendars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @calendar.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @calendar.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @calendar.user_id %>
</p>

<div>
  <p>Work Schedules</p>
  <%= link_to "Schedules", schedules_path %>
</div>

  <div class="max-w-lg">
  <%= month_calendar(events: @appointments) do |date, appointments| %>
    <%= date.day %>

    <% appointments.each do |appointment| %>
      <div style="color: #FFC; padding: 4px; background-color: #64a1d1; margin-bottom:1px;">
      <% if appointment.check_availability %>
        <%= appointment.id %> - <%= appointment.start_time.strftime("%I:%M%p") %>
      <% else %>
        Booked - <%= appointment.start_time.strftime("%I:%M%p") %>
      <% end%>
      </div>
    <% end %>
  <% end %>
  </div>


<%= link_to 'Edit', edit_calendar_path(@calendar) %> |
<%= link_to 'Back', calendars_path %>