config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  #resources :form_entries
  resources :calendars
  resources :forms do 
    resources :form_entries
  end 
  resources :schedules
  resources :availabilities
  devise_for :users

  root to: 'dashboards#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
    def index 
        @calendar = Calendar.first
        @appointments = @calendar.appointments.current_month
        @availabilities = @calendar.availabilities.current_month
        @forms = @calendar.forms.all
    end 
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboards/index.html.erb
<div class="py-8 space-y-4">
<h1 class="text-xl font-bold">Appointments Demo</h1>

<div>
  <div><h2 class="text-lg">Calendars</h2></div>

  <div>You are on Calendar ID:<%= @calendar.id %> </div>
  <div>This Calendar is split into <%= @calendar.interval %> minute intervals</div>
</div>

<div class="space-y-2">
  <div><h2 class="text-lg">Availability this month</h2> <span>Define when appointments can be scheduled based off of Calendar interval time.</span></div>
  <% @availabilities.each do |a| %>
      <ul>
          <li><%= local_time(a.start_time) %> -> <%= local_time(a.end_time) %> <%= link_to "View", availability_path(a), class: "ml-2 text-blue-400 hover:text-blue-500" %></li>
      </ul>
  <% end %>
</div>
  <div class="mt-5">
  <%= link_to "Add Availability", new_availability_path, class: "btn-primary" %>
  </div>

<div class="grid sm:grid-cols-2 gap-5">

  <div class="space-y-2">
    <div><h2 class="text-lg">Form Entries</h2>  <span>In order to book appointment, you must submit a form</span></div>
    <% @forms.each do |form| %>
        <div class="space-y-2">
            <div class="flex items-center justify-between">
              <h4 class="underline">Name: <%= form.name %></h4>
              <div>
                <%= link_to "New Form Entry", new_form_form_entry_path(form), class: "btn-primary" %>
              </div>
            </div>
            <p class="underline">Entries:</p>
            <ul class="space-y-1">
            <% form.form_entries.each_with_index do |entry, index| %>
                <li class="text-sm"><%= index %> <%= entry.name %> - <%= entry.phone %> - <%= entry.email %> - <%= local_time(entry.appointments.first.start_time) %></li>
            <% end %>
            </ul>
        </div>
    <% end %>
  </div>
  <div>
    <div><h2 class="text-lg">Appointments this month</h2> <span>Every booked appointment. Appts can't be booked individually without form submit</span></div>
    <% @appointments.each do |appt| %>
        <ul>
            <li><%= local_time(appt.start_time) %></li>
        </ul>
    <% end %>
  </div>
</div>

<div>
    <div class="max-w-7xl border p-5">
    <%= month_calendar(events: @appointments) do |date, appointments| %>
      <%= date.day %>

      <% appointments.each do |appointment| %>
        <div class="text-white px-1.5 py-1 bg-blue-500 mb-1 text-xs rounded-lg">
        <% if appointment.check_availability %>
          <%= appointment.id %> - <%= appointment.start_time.strftime("%I:%M%p") %>
        <% else %>
          Booked - <%= local_time(appointment.start_time.strftime("%I:%M%p")) %>
        <% end%>
        </div>
      <% end %>
    <% end %>
    </div>
  </div>

  </div>