config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  #resources :form_entries
  resources :calendars
  resources :forms do 
    resources :form_entries
  end 
  resources :schedules
  resources :availabilities
  devise_for :users

  root to: 'dashboards#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/form_entry.rb
class FormEntry < ApplicationRecord
  belongs_to :form
  has_many :appointments
  accepts_nested_attributes_for :appointments, allow_destroy: true

  # has_many :entry_appointments, :dependent => :destroy 
  # has_many :appointments, through: :entry_appointments
  # accepts_nested_attributes_for :entry_appointments

  validates :name, presence: true
  # validates_associated :entry_appointments, :appointments
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i, message: "Please enter a valid email address" }, length: { minimum: 4, maximum: 254 }
  validates :phone, format: { with: /\A(?:\+?\d{1,3}\s*-?)?\(?(?:\d{3})?\)?[- ]?\d{3}[- ]?\d{4}\z/, message: 'Please enter a valid phone number.' }

end

app/controllers/form_entries_controller.rb
class FormEntriesController < ApplicationController
  before_action :set_form_entry, only: %i[ show edit update destroy ]

  # GET /form_entries or /form_entries.json
  def index
    @form_entries = FormEntry.all
  end

  # GET /form_entries/1 or /form_entries/1.json
  def show
  end

  # GET /form_entries/new
  def new
    @form = Form.find(params[:form_id])
    @form_entry = FormEntry.new
    @form_entry.appointments.build
    
    
    # If Form is attached to calendar, create availabilities variable
    if @form.calendars.any?
      @availabilities = @form.calendars.first.availabilities
      @avail = Availability.in_range_of_start((DateTime.now - 3)..(DateTime.now + 4))
    end 
  end

  # GET /form_entries/1/edit
  def edit
    @appointments = Appointment.all
  end

  # POST /form_entries or /form_entries.json
  def create
    @form = Form.find(params[:form_id])
    @form_entry = @form.form_entries.new(form_entry_params)

    respond_to do |format|
      if @form_entry.save
        format.html { redirect_to form_form_entry_path(params[:form_id], @form_entry.id), notice: "Form entry was successfully created." }
        format.json { render :show, status: :created, location: @form_entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @form_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /form_entries/1 or /form_entries/1.json
  def update
    respond_to do |format|
      if @form_entry.update(form_entry_params)
        format.html { redirect_to @form_entry, notice: "Form entry was successfully updated." }
        format.json { render :show, status: :ok, location: @form_entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @form_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /form_entries/1 or /form_entries/1.json
  def destroy
    @form_entry.destroy
    respond_to do |format|
      format.html { redirect_to form_entries_url, notice: "Form entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form_entry
      @form_entry = FormEntry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def form_entry_params
      params.require(:form_entry).permit(:name, :email, :phone, :form_id, appointments_attributes:[:start_time, :end_time, :calendar_id])
    end
end

app/helpers/form_entries_helper.rb
module FormEntriesHelper
end

app/views/form_entries/_form.html.erb
<%= form_for [@form, form_entry] do |form| %>
  <% if form_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(form_entry.errors.count, "error") %> prohibited this form_entry from being saved:</h2>

      <ul>
        <% form_entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="max-w-lg py-8">
    <div class="space-y-2">
      <div>  
        <p>You are on <%= @form.name %></p>
        <p>You are on Calendar: <%= @form.calendars.first.name %></p>
      </div>
      <div class="relative block">
        <%= form.text_field :name, class: "shadow border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-blue-500 focus:shadow-outline", placeholder: true %>
      </div>

      <div class="relative block">
        <%= form.text_field :email, class: "shadow border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-blue-500 focus:shadow-outline", placeholder: true %>
      </div>

      <div class="relative block">
        <%= form.text_field :phone, class: "shadow border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-blue-500 focus:shadow-outline", placeholder: true %>
      </div>
    </div>
  </div>

  <div data-controller="book-appointment">

    <div class="space-y-2 border border-gray-300 p-2 mb-5">
      <%= form.fields_for :appointments do |f| %>
        <h3 class="text-md font-semibold">Book an Appointment Time</h3>
        <p>These would normally be hidden fields that hold input data, but show that Stimulus injects into the fields</p>
        <div class="field">
          <%= f.label :start_time %>
          <%= f.text_field :start_time, class: 'border border-gray-300', data: { "book-appointment-target": "start"} %>
        </div>
        <div class="field">
          <%= f.label :end_time %>
          <%= f.text_field :end_time, class: 'border border-gray-300', data: { "book-appointment-target": "end"}  %>
        </div>
        <div class="field">
          <%= f.label :calendar_id %>
          <%= f.number_field :calendar_id, value: @form.calendars.first.id, class: 'border border-gray-300' %>
        </div>
      <% end %>
    </div>
    
    <% if @availabilities.present? %>
    <% if @avail.present? %>
    <div class="max-w-7xl">
      <h2 class="text-lg font-bold">Availabilities this Week</h2> 
      <div class="relative block space-y-3 grid grid-cols-2 xl:grid-cols-4 gap-4">
        <% @avail.each do |a| %>
          <div class="h-72 overflow-y-scroll w-auto p-2 border border-gray-300 rounded-xl">
            <p class="text-xl mb-3"><%= a.start_time.strftime('%B %e') %></p>
            <% a.list_slots.each do |slot| %>
                <%= tag.span id: dom_id(a, :slot), class: "relative block w-auto bg-green-300 rounded-md shadow px-4 py-3 cursor-pointer hover:bg-green-100 mb-2", data: {
                  "book-appointment-target": "slot", action: "click->book-appointment#fire", start_time: slot[:start_time], end_time: slot[:end_time] } do %>
                  <%= local_time(slot[:start_time]) %>
                <% end %>
          <% end %>
          </div>
        <% end %>
      </div>
      <% end %>
    </div>

    <% else %>
    <p>There are no available times to book.</p>
    <% end %>

  </div>

  

  <div class="actions">
    <%= form.submit "Submit Form", class: 'btn-primary' %>
  </div>
<% end %>

app/views/form_entries/edit.html.erb
<h1>Editing Form Entry</h1>

<%= render 'form', form_entry: @form_entry %>

<%= link_to 'Show', @form_entry %> |
<%= link_to 'Back', form_entries_path %>

app/views/form_entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Form Entries</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Appt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @form_entries.each do |form_entry| %>
      <tr>
        <td><%= form_entry.id %></td>
        <td><%= form_entry.name %></td>
        <td><%= form_entry.email %></td>
        <td><%= form_entry.phone %></td>
        <td><%= form_entry.appointments.first.start_time.strftime("%D %I:%M%p") if form_entry.appointments.present? %> - <%= form_entry.appointments.first.end_time.strftime("%D %I:%M%p") if form_entry.appointments.present? %></td>
        <td><%#= link_to 'Show', form_form_entry_path(form_entry) %></td>
        <td><%#= link_to 'Edit', edit_form_entry_path(form_entry) %></td>
        <td><%#= link_to 'Destroy', form_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Form Entry', new_form_entry_path %>

app/views/form_entries/new.html.erb
<h1>New Form Entry</h1>

<%= render 'form', form_entry: @form_entry %>

<%#= link_to 'Back', form_entries_path %>

app/views/form_entries/show.html.erb
<div class="container p-4">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @form_entry.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @form_entry.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @form_entry.phone %>
</p>

<p>
  <strong>Form:</strong>
  <%= @form_entry.form_id %>
</p>

<div class="mt-4">
<%= link_to 'Back to Main', root_path, class: 'btn-primary' %>
</div>
</div>